#COST 3.75
SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos A;

# COST 39394.50
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;

# COST 127190.25
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO;

# 127190.25 --> EL GROUP BY Y EL ORDER BY NO AUMENTA CONSIDERABLEMENTE LA CONSULTA
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANO, SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) ORDER BY  A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA);

/*Hay un comando llamado explain que nos indica el plan de ejecucion que nos permite tomar decisiones para mejorar
el rendimiento y tener un impacto en el desempeño de las Query*/

